[package]
name = "denoflate"
version = "0.1.0"
authors = ["TTtie <tttiett@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
inflate = "0.4.5"
deno_core = "0.48.0"