name: Code Quality - TypeScript

on:
    push:
        branches:
            - master
        paths:
            - mod.ts

jobs:
    build:
        name: Linting
        runs-on: ubuntu-latest
        timeout-minutes: 60

        steps:
            - name: Clone repository
              uses: actions/checkout@v1
            - name: Show deno version
              uses: Denocord/deno-action@v1
              with:
                args: ["--version"]
            - name: Lint
              uses: Denocord/deno-action@v1
              with:
                args: ["fmt", "mod.ts"]
