name: Code Quality - TypeScript

on:
    push:
        branches:
            - master
        paths:
            - mod.ts

jobs:
    build:
        name: Linting
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            - name: Lint
              uses: Denocord/deno-action@master
              with:
                args: '["fmt", "--check", "mod.ts"]'
