name: PR

on: [pull_request]
jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        timeout-minutes: 60
        strategy:
            matrix:
                os: [ macos-latest, windows-latest, ubuntu-latest ]
        steps:
            - name: Clone repository
              uses: actions/checkout@v1

            - name: Install rust
              uses: hecrj/setup-rust-action@v1
              with:
                rust-version: "1.43.1"

            - name: Build
              env:
                RUST_BACKTRACE: 1
              run: cargo build --release